name: Pylint and Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.9"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint -r requirements.txt

      # Pylint Step: Only run on Python 3.9
      - name: Pylint Analysis
        run: pylint $(git ls-files '*.py')

      # Unit Test Step: Run on all Python versions
      - name: Run Unit Tests
        run: python -m unittest discover -s tests -p "test_*.py"
